name: build-master

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.mvn/**'
      - 'mvnw'
      - 'mvnw.cmd'
      - 'README.md'
      - '.gitignore'

  pull_request:
    branches:
      - master
    paths-ignore:
      - '.mvn/**'
      - 'mvnw'
      - 'mvnw.cmd'
      - 'README.md'
      - '.gitignore'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Start Database
        run: ./setup-database.bash

      - name: Build project
        run: mvn clean install

      - name: Show test result
        run: mvn surefire-report:report-only
             cat target/site/surefire-report.html

      - name: Publish to GitHub Packages
        run: |
          echo "//maven.pkg.github.com/karunaproject/be/:registryToken=$GITHUB_TOKEN" > .npmrc
          mvn deploy -Dmaven.deploy.skip=true -Dmaven.repo.local=$HOME/.m2/repository
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}